version: '3.7'

services:
## POSTGRESQL
  db:
    image: postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/my_data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

## DJANGO APP
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jblchat
    # command:
    #   sh -c "python jbl_chat/manage.py migrate 
    #   && 
    #   python manage.py mock_users
    #   &&
    #   python jbl_chat/manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      - db

## REDIS
  redis:
    image: redis:alpine
    container_name: jbl_cache
    ports:
      - "6379:6379"

## CELERY
  celery:
    restart: always
    build:
      context: .
    command: sh -c "cd jbl_chat && celery -A jbl_chat worker -l info"
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

## FLOWER
  flower:
    image: mher/flower:1.0.0
    build:
      context: .
    command: sh -c "cd jbl_chat && celery -A jbl_chat flower -l info -p 5555"
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - celery
      - redis
      - web