version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jblchat
    # command: /start
    #   sh -c "python manage.py"
      # sh -c "python jbl_chat/manage.py migrate && python jbl_chat/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8081:8081"
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"